### ISSUE TITLE
Feature no disponible 

### ISSUE THREAD

**Issue by SericCocom** [FacturAPI/facturapi-php#15]
Utilizo la funcionalidad para cargar el catalogo de articulos

```
$facturapi = new Facturapi($key);
        return $facturapi->Catalogs->searchProducts([
            'q' => request('search')
        ]);
```

Pero al momento de hacer la consulta, me arroja lo siguiente
```
{
"message": "Feature no disponible.",
"ok": false
}
```

Algún error en integración? Help!!!!1

**Comment by fobos235** [comment]
Yo tengo este mismo problema

**Comment by SericCocom** [comment]
> Yo tengo este mismo problema
Según me dijeron, esta funcionalidad ahora es de paga, por lo tanto ya no se puede usar de manera free. Para solucionarlo debes de contratar una suscripción al plan donde está incluido.

**Comment by SericCocom** [comment]
esta funcionalidad ahora es de paga, por lo tanto ya no se puede usar de manera free. Para solucionarlo debes de contratar una suscripción al plan donde está incluido.
