### ISSUE TITLE
customs_keys

### ISSUE THREAD

**Issue by 10141150** [FacturAPI/facturapi-php#9]
after creating a Invoice this message was returned:
object(stdClass)#14 (2) { ["message"]=> string(58) ""items[0]" > "customs_keys" must contain at least 1 items" ["ok"]=> bool(false) }

**Comment by javorosas** [comment]
Tal vez estás enviando un arreglo vacío. La solución parece ser no enviar la propiedad en primer lugar. De cualquier manera, esto concierne a la API, no a la librería. Voy a cerrar el issue.
